### ISSUE TITLE
blockchain-export/import AFTER SECOR failure.

### ISSUE THREAD

**Issue by camthegeek** [masari-project/masari#179]
blockchain-import fails somewhere after block 363000. See error below.

`2019-07-08 17:48:30.782     7f0dc2940bc0        FATAL   bcutil  src/blockchain_utilities/blockchain_import.cpp:546      exception while reading from file, height=363605: Error in deserialization of chunk`

This could be a failure on blockchain-export as well (or both). 

File being tested is https://chain.masari.rocks/blockchain.raw but feel free to use your own export for testing. guard-against-pwnage was also set to zero. 

363605 in @gnock's block explorer -> https://explorer.masari.rocks/block.html?height=363605

I'm left to assume this is an uncle and is why the export/import is failing.

**Comment by cryptochangements34** [comment]
Which version are you running?

**Comment by camthegeek** [comment]
> Which version are you running?

Good catch. My masari.rocks node was still on 3.0.0 after I thought I had replaced files and restarted daemon. I updated to latest version (3.1.2), exported and imported on a different server and all was fine.
