### ISSUE TITLE
Numerous security issues with this set of files.

### ISSUE THREAD

**Issue by epb5119** [masari-project/masari#31]
Windows 10 OS
Almost every file i unzipped caused Windows Defender security block. Numerous attempts to exclude these files failed. I am experienced with many GUI wallets and this one is by far the worst experience I had so far.

**Comment by thaerkh** [comment]
This is a third-party software issue and not related to Masari. You can find Microsoft support here: https://support.microsoft.com/en-ca/contactus/

**Comment by epb5119** [comment]
This related to your recently released Masari GUi wallet. has nothing to do with Microsoft..

**Comment by thaerkh** [comment]
You stated that Windows Defender is raising warnings on MSR binaries and are unable to place exceptions, that's a Microsoft product issue.
Cryptocurrency binaries these days are typically flagged by antivirus software under the assumption that the end user doesn't understand what they're downloading, in case they're downloading malware that would surreptitiously mine using their hardware.
We haven't launched new GUI wallet binaries, where did you get these? anything that's not from our Github project is not official and could be a security risk.

**Comment by thaerkh** [comment]
Closing, as I'm going to assume issue is resolved. If you've downloaded GUI binaries from a third party, please let me know of the source.

Thanks,
Thaer
