### ISSUE TITLE
error when building docker image

### ISSUE THREAD

**Issue by mouradski** [masari-project/masari#36]
Hi, 

i got this erreur when i try to build docker image :

[Dockerfile.zip](https://github.com/masari-project/masari/files/1976439/Dockerfile.zip)

`make[2]: Leaving directory '/usr/local/libsodium'
make[1]: Leaving directory '/usr/local/libsodium'
Removing intermediate container 8872400226c8
 ---> cfdf3620f3e1
Step 24/35 : WORKDIR /src
Removing intermediate container 69c80cd29275
 ---> 6343fdcb21f1
Step 25/35 : COPY . .
 ---> 6f30e22756df
Step 26/35 : ARG NPROC
 ---> Running in c6f3cf1a4886
Removing intermediate container c6f3cf1a4886
 ---> 4b52ff37e1b9
Step 27/35 : RUN rm -rf build &&     if [ -z "$NPROC" ];then make -j$(nproc) release-static;else make -j$NPROC release-static;fi
 ---> Running in 99f1d3c9a9ad
make: *** No rule to make target 'release-static'.  Stop.
The command '/bin/sh -c rm -rf build &&     if [ -z "$NPROC" ];then make -j$(nproc) release-static;else make -j$NPROC release-static;fi' returned a non-zero code: 2`

**Comment by mouradski** [comment]
Makefile contains release-static target, it apears it don't use the right makefile

**Comment by mouradski** [comment]
https://github.com/masari-project/masari/pull/40 should fix

**Comment by thaerkh** [comment]
merged, thank you
