### ISSUE TITLE
Error: internal error: Known ring does not include the spent output: 722396

### ISSUE THREAD

**Issue by ducho** [masari-project/masari#37]
Hi.
Today morning on my previous wallet  masari-mac-x64-v0.2.0.2 i did transaction but I didn't found this transaction in block explorer after 2 hours. I have found new version mac-wallet-cli and after update my wallet refresh my previous balance before transfer. 

Now I doing new transfer and still unsucceable with error:
```Error: internal error: Known ring does not include the spent output: 722396```
What I can do for success transfer ?

**Comment by ducho** [comment]
solved

**Comment by jamescanningcooke** [comment]
Same problem with GUI 12.2.0 as with 12.0.00. 
Tried to send a transaction from GUI wallet, and same error message: Can't create transaction: internal error: Known ring does not include the spent output: xxxxxxx
