### ISSUE TITLE
New difficulty algorithm

### ISSUE THREAD

**Issue by zawy12** [masari-project/masari#5]
We've developed a new algorithm that's the best of the best and allows integer math on the target.

https://github.com/zawy12/difficulty-algorithms/issues/17

**Comment by nesterow** [comment]
[Bytecoin Issue](https://github.com/amjuarez/bytecoin/issues/202) related to the difficulty adjustment and time-warp attacks.

**Comment by 4Reallive** [comment]
So is the above proposed difficulty algorithm going into the base? Very Interested in learning more about this.

**Comment by zawy12** [comment]
Masari is using the best difficulty algorithm I know of and I don't recommend a change.
