### ISSUE TITLE
build on Mac OSX fails

### ISSUE THREAD

**Issue by cryptonote-social** [masari-project/masari#53]
I have verified this patch for Monero worked for me in Masari:

https://github.com/monero-project/monero/pull/3667

**Comment by arcmags** [comment]
Can confirm that building Masari as is currently fails with boost 1.67 on Arch Linux.

Here is a [patch](https://github.com/arcmags/xmr-mine/blob/master/pkgbuild/masari/boost1.67.patch) to fix the issue as well as working Arch Linux [build files](https://github.com/arcmags/xmr-mine/tree/master/pkgbuild/masari).

Pull request: #55

**Comment by cryptochangements34** [comment]
@arcmags Thanks for looking into this. #56 included a fix for this along with others and has been merged.

**Comment by thaerkh** [comment]
@cryptonote-social we'd like to send you some MSR for reporting this, do you mind sending us an address?

**Comment by cryptonote-social** [comment]
Cool, thanks!

5rDQMppyTjbiAaiVftJYV4jhF3HwrL2DM3bWvgJecQddcHgUFhrRiizCE3mq6Pu5KDXxYT17ck77qZd8j2W1bPSJU5FWfLu

**Comment by thaerkh** [comment]
cheers https://www.msrchain.net/search?value=009c189b52fa2035074206a2c561b63d0588239027f0bf4a8e105b252cacbcc1
