### ISSUE TITLE
Endpoint get_transaction_pool returning invalid json characters

### ISSUE THREAD

**Issue by gnock** [masari-project/masari#93]
According to the IETF, a [json string cannot contains binary values](https://tools.ietf.org/html/rfc7159#section-7).

`curl -X POST http://127.0.0.1:48081/get_transaction_pool -d '{}' -H 'Content-Type: application/json'`
returns something like 
`
{
  "spent_key_images": [],
  "status": "OK",
  "transactions": [{
    "blob_size": 14594,
    "do_not_relay": false,
    "double_spend_seen": false,
    "fee": 12774300000,
    "id_hash": "16e7427fb322eccaf6e9d3a32165ea17c87195a00fa052eed1324261ce156c07",
    "kept_by_block": false,
    "last_failed_height": 0,
    "last_failed_id_hash": "0000000000000000000000000000000000000000000000000000000000000000",
    "last_relayed_time": 1536520613,
    "max_used_block_height": 263363,
    "max_used_block_id_hash": "2b6dacf863929c19eedb1e22f239f164d412ff8a7399c3013033ae97a5ce9eeb",
    "receive_time": 1536520613,
    "relayed": true,
    "tx_blob": "DATA",
	"tx_json": "JSON_VALUE"
  }],
  "untrusted": false
}
`

Sadly the tx_blob returns binary characters including the NULL character (0x0). It's impossible from a browser to parse this endpoint properly as the internal system do not store the content past the null character.

One possible alternative would be to add a parameter asking to not return the tx_blob. It will only also remove duplicate content.

**Comment by cryptochangements34** [comment]
Addressed in #93
