### ISSUE TITLE
Optimize the result of RPC endpoints

### ISSUE THREAD

**Issue by gnock** [masari-project/masari#95]
Some endpoints returns duplicated content. It can be problematic on non wireless networks due to the cost of data.

Currently at least one endpoint has this problem. If more are found, i add them as comments and edit this post.

The endpoint /gettransactions  (with {"decode_as_json":true,"txs_hashes":["24d2023bc3031baabf48409bb356eda31fd008441599f92875c03ca93da4cdc9"]} ) as parameter) returns this kind of content:
`
{
  "status": "OK",
  "txs": [{
    "as_hex": "HEX_VALUE",
    "as_json": "JSON_VALUE",
    "block_height": 255000,
    "block_timestamp": 1535516465,
    "double_spend_seen": false,
    "in_pool": false,
    "output_indices": [1149145,1149146],
    "tx_hash": "24d2023bc3031baabf48409bb356eda31fd008441599f92875c03ca93da4cdc9"
  }],
  "txs_as_hex": ["HEX_VALUE"],
  "txs_as_json": ["JSON_VALUE"],
  "untrusted": false
}
`
Json values and hex values are present 2 times.
Also, when we explicitly ask for json, it could means we dont want the json value. 

We could add a parameter to not receive the hex value to decrease the global data size.

**Comment by cryptochangements34** [comment]
Addressed in #100

**Comment by cryptochangements34** [comment]
#101 also
